name: Build

on:
  push:
    branches: [deploy-v2]

jobs:
  extract_tag:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract the tag
      id: get_tag
      run: |
        tag=${GITHUB_REF#refs/tags/}  # Strip 'refs/tags/' to get the tag name
        echo "Tag is: $tag"
        echo "::set-output name=tag::$tag"  # Set the output as the tag
   
    outputs: 
      ref: ${{ steps.get_tag.outputs.tag }}

  build:
    runs-on: ubuntu-latest
    needs: extract_tag
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build Linux
        run: |
          build_time=$(date "+%Y-%m-%d_%H:%M:%S")
          go build -ldflags="-X main.version=${{ needs.extract_tag.outputs.ref }} -X main.releaseDate=$build_time"  -v -o ./build/goml-${{ needs.extract_tag.outputs.ref }}-linux-amd64/goml
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
          CXX: "x86_64-linux-musl-g++"
      # - name: Test with the Go CLI
      #   run: go test
      - name: Deploy with rsync
        run: rsync -avz ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/mlayer/binaries/
      - name: Deploy Node 1
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{ secrets.SSH_PASS }}

          script: |
            ./mlayer-deploy_v3.sh
  
     

  

    
