name: Build and deploy
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Deploy Node 1
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{ secrets.SSH_PASS }}

          script: |
            ./mlayer-deploy_v2.sh
