name: Build and deploy

on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy Node
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{ secrets.SSH_PASS }}

          script: |
            ./mlayer-deploy.sh
